### PR TITLE
Aboutpage

### PR DESCRIPTION
**Pull request by marykatefain**
Attempting to submit pull request for this as per Alex's request.

### CODE REVIEW

**Comment by alexgleason** [comment]
Lol this is a comment thread. You're supposed to be like "this is the about page, I've added XYZ things", etc.

**Comment by alexgleason** [comment]
Looks good though. I'll merge and push.

**Comment by marykatefain** [comment]
This is an about page, I vaguely remember putting things about DxE on it. Also edited the home page content and created a button to the new page.

**Comment by alexgleason** [comment]
Lol okay. I've merged it. Deploying now

**Pull request merged**
